openapi: 3.0.0
info:
  version: 1.0.0
  title: Analyzer Service API
  description: API to analyze rainfall and flooding event messages from Kafka.
paths:
  /event1:
    get:
      summary: Retrieve a specific rainfall event by index
      operationId: app.get_rainfall_event
      parameters:
        - name: index
          in: query
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Retrieved the rainfall event
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RainConditions"
        "404":
          description: Event not found
  /event2:
    get:
      summary: Retrieve a specific flooding event by index
      operationId: app.get_flooding_event
      parameters:
        - name: index
          in: query
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Retrieved the flooding event
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Floodings"
        "404":
          description: Event not found
  /stats:
    get:
      summary: Retrieve statistics about stored events
      operationId: app.get_event_statistics
      responses:
        "200":
          description: Successfully retrieved event statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  num_rain_conditions:
                    type: integer
                    description: Number of recorded rain events
                  num_flooding_events:
                    type: integer
                    description: Number of recorded flooding events
components:
  schemas:
    RainConditions:
      required:
        - trace_id
        - device_id
        - rain_location_longitude
        - rain_location_latitude
        - rainfall_nm
        - intensity
        - timestamp
      type: object
      properties:
        trace_id:
          type: string
          description: The unique ID of the trace
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        device_id:
          type: string
          description: The unique ID of the device reporting all the data
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        rain_location_longitude:
          type: integer
          description: Longitude of the location
          example: 101
        rain_location_latitude:
          type: integer
          description: Latitude of the location
          example: 200
        rainfall_nm:
          type: integer
          description: Amount of rainfall
          example: 100
        intensity:
          type: string
          description: Intensity of rainfall (light, moderate, heavy)
          example: Extreme
        timestamp:
          type: string
          format: date-time
          example: 2011-10-10T14:48:00
    Floodings:
      required:
        - trace_id
        - device_id
        - flood_location_longitude
        - flood_location_latitude
        - flood_level
        - severity
        - timestamp
      type: object
      properties:
        trace_id:
          type: string
          description: The unique ID of the trace
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        device_id:
          type: string
          description: Identifies the device that reported the flooding
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        flood_location_longitude:
          type: integer
          description: Longitude of the flooding location
          example: 101
        flood_location_latitude:
          type: integer
          description: Latitude of the flooding location
          example: 200
        flood_level:
          type: integer
          description: Depth of floodwater in centimeters
          example: 150
        severity:
          type: string
          description: Describes the impact or severity of the flooding (e.g., "low," "medium," "high," "critical")
          example: The flood is critical; evacuation is necessary.
        timestamp:
          type: string
          format: date-time
          example: 2025-01-10T14:48:00
