datastore:
  filename: "data/processing/stats.json"

scheduler:
  interval: 10

eventstores:
  RainConditions:
    url: "http://storage:8090/storage/rain/RainConditions"
  floodings:
    url: "http://storage:8090/storage/rain/floodings"
